import type { RouteKey } from './routes'

export type GrowthCard = { title: string; text: string }
export type GrowthLink = { href: string; label: string }

export type GrowthPage = {
  kind: 'service' | 'solution'
  kicker: string
  h1: string
  lead: string
  intro: string[]
  problemsTitle: string
  problemsIntro: string
  problems: GrowthCard[]
  audienceTitle: string
  audienceIntro: string
  audience: GrowthCard[]
  solutionsTitle: string
  solutionsIntro: string
  solutions: GrowthCard[]
  benefitsTitle: string
  benefits: GrowthCard[]
  processTitle: string
  processIntro: string
  process: GrowthCard[]
  faqs: GrowthCard[]
  caseStudy: GrowthLink & { name: string; text: string }
  related: GrowthLink[]
  ctaTitle: string
  ctaText: string
  ctaLabel: string
  whatsappMessage: string
}

export const GROWTH_PAGES: Partial<Record<RouteKey, GrowthPage>> = {
  'software-a-la-medida': {
    kind: 'service',
    kicker: 'Digitalización de procesos',
    h1: 'Software a la medida para empresas',
    lead: 'Construimos sistemas que se adaptan a la forma real de operar de tu empresa, conectan la información y reemplazan tareas manuales que ya frenan el crecimiento.',
    intro: [
      'El software a la medida tiene sentido cuando el negocio necesita algo más preciso que una herramienta genérica. En lugar de obligar al equipo a modificar procesos valiosos para encajar en un programa, diseñamos una solución alrededor de sus roles, reglas, datos y decisiones cotidianas.',
      'El punto de partida no es una lista de funciones. Analizamos dónde se pierde tiempo, qué información se repite, quién necesita intervenir y qué resultado debe mejorar. Con ese mapa definimos una primera versión útil, medible y preparada para evolucionar sin convertir el proyecto en una implementación interminable.',
    ],
    problemsTitle: 'Señales de que una herramienta genérica ya no es suficiente',
    problemsIntro: 'Un sistema propio no se justifica por ser más sofisticado, sino porque resuelve fricciones que afectan la operación, la trazabilidad o la capacidad de atender más trabajo.',
    problems: [
      { title: 'La información vive en varios archivos', text: 'Cada área conserva su propia versión de los datos y el equipo dedica tiempo a comparar hojas, corregir duplicados o preguntar cuál documento está actualizado.' },
      { title: 'El proceso depende de memoria y mensajes', text: 'Los pasos importantes se recuerdan por experiencia, se coordinan por chats y quedan expuestos cuando una persona no está disponible o cambia de función.' },
      { title: 'Las herramientas no reflejan las reglas del negocio', text: 'El equipo hace cálculos, validaciones y controles por fuera del sistema porque el producto estándar no contempla condiciones propias de la operación.' },
      { title: 'Crecer aumenta el desorden', text: 'Más pedidos, clientes o colaboradores generan más trabajo administrativo. La empresa vende más, pero también multiplica revisiones, reprocesos y puntos de error.' },
      { title: 'No existe una vista confiable del estado actual', text: 'Preparar un informe exige recopilar datos manualmente y las decisiones se toman con cifras atrasadas, incompletas o difíciles de verificar.' },
    ],
    audienceTitle: '¿Para qué empresas sirve el software a la medida?',
    audienceIntro: 'Es una opción especialmente útil para pequeñas y medianas empresas que ya conocen bien su operación y necesitan convertir ese conocimiento en una herramienta compartida.',
    audience: [
      { title: 'Operaciones con pasos y permisos propios', text: 'Empresas donde un pedido, servicio o expediente pasa por varias áreas y cada rol necesita ver, aprobar o completar información diferente.' },
      { title: 'Equipos que superaron Excel', text: 'Negocios que empezaron con hojas de cálculo funcionales, pero ahora necesitan colaboración, historial de cambios, control de acceso y datos centralizados.' },
      { title: 'Empresas que quieren integrar su ecosistema', text: 'Organizaciones con plataformas existentes que necesitan compartir información mediante APIs, evitar la doble digitación y mantener una fuente única de verdad.' },
    ],
    solutionsTitle: 'Qué podemos construir alrededor de tu operación',
    solutionsIntro: 'La solución se define después del diagnóstico. Estas son capacidades frecuentes, no un paquete rígido que todas las empresas deban comprar.',
    solutions: [
      { title: 'Plataformas administrativas', text: 'Centralizan clientes, documentos, tareas, estados, responsables y reglas de aprobación en un entorno accesible para cada equipo.' },
      { title: 'Sistemas de pedidos e inventario', text: 'Conectan la captura de solicitudes con disponibilidad, preparación, despacho, facturación y seguimiento para conservar la historia completa.' },
      { title: 'CRM y seguimiento comercial', text: 'Organizan oportunidades, conversaciones, compromisos y próximas acciones sin separar la venta del contexto operativo del cliente.' },
      { title: 'Dashboards y reportes', text: 'Transforman la información registrada durante el trabajo en indicadores comprensibles, filtros útiles y alertas para tomar decisiones oportunas.' },
      { title: 'Integraciones y automatizaciones', text: 'Comunican servicios actuales, ejecutan acciones repetitivas y reducen los traspasos manuales sin reemplazar herramientas que todavía cumplen bien su función.' },
    ],
    benefitsTitle: 'Resultados que debe producir una solución bien planteada',
    benefits: [
      { title: 'Una sola versión de la información', text: 'Los equipos consultan datos actualizados y relacionados, con menos archivos paralelos y menos tiempo dedicado a confirmar estados.' },
      { title: 'Procesos visibles y repetibles', text: 'Cada persona sabe qué debe hacer, qué ocurrió antes y qué condición permite avanzar al siguiente paso.' },
      { title: 'Menos trabajo operativo innecesario', text: 'Validaciones, notificaciones, cálculos y actualizaciones pueden ejecutarse dentro del flujo para que el equipo se concentre en las excepciones.' },
      { title: 'Capacidad de evolucionar', text: 'La arquitectura y las entregas por etapas permiten incorporar prioridades nuevas conforme el negocio aprende, sin rehacer toda la plataforma.' },
    ],
    processTitle: 'Cómo desarrollamos software a la medida',
    processIntro: 'Reducimos incertidumbre antes de escribir código y dividimos el alcance para que la empresa pueda validar decisiones durante el proyecto.',
    process: [
      { title: 'Diagnóstico del proceso', text: 'Conversamos con quienes ejecutan el trabajo, identificamos entradas, decisiones, excepciones y resultados esperados.' },
      { title: 'Mapa de oportunidades', text: 'Separamos lo esencial de lo conveniente y señalamos qué puede simplificarse antes de trasladarlo a una pantalla.' },
      { title: 'Diseño de la solución', text: 'Definimos flujos, roles, estructura de información y un prototipo navegable para validar el uso antes del desarrollo.' },
      { title: 'Construcción por etapas', text: 'Entregamos módulos funcionales, revisamos escenarios reales y ajustamos prioridades con evidencia del producto en uso.' },
      { title: 'Implementación', text: 'Preparamos datos, accesos y acompañamiento para que el cambio sea comprensible y no interrumpa la operación.' },
      { title: 'Soporte y evolución', text: 'Atendemos ajustes, observamos la adopción y planificamos mejoras de acuerdo con nuevas necesidades del negocio.' },
    ],
    faqs: [
      { title: '¿Cuándo conviene desarrollar en lugar de comprar?', text: 'Cuando el proceso aporta una diferencia real al negocio, exige reglas particulares o las herramientas disponibles provocan más trabajo paralelo del que eliminan. En el diagnóstico también revisamos si configurar una solución existente sería suficiente.' },
      { title: '¿Es necesario definir todo desde el inicio?', text: 'No. Sí necesitamos comprender el problema y el resultado esperado. A partir de ahí proponemos una primera etapa concreta, con límites claros y espacio para aprender antes de comprometer funcionalidades posteriores.' },
      { title: '¿Pueden reemplazar gradualmente archivos de Excel?', text: 'Sí. Es frecuente comenzar por el punto que concentra más riesgo o duplicación, importar la información necesaria y mantener una transición controlada mientras el equipo adopta el nuevo flujo.' },
      { title: '¿El sistema puede conectarse con otras plataformas?', text: 'Depende de las APIs y condiciones de cada servicio. Evaluamos la viabilidad técnica, los permisos y el comportamiento esperado antes de incluir una integración en el alcance.' },
      { title: '¿Qué sucede después de publicar?', text: 'Acompañamos la implementación, atendemos ajustes y conservamos el contexto del producto para que pueda evolucionar. El soporte se define según la criticidad y el ritmo de cambio de cada operación.' },
    ],
    caseStudy: { name: 'Fórmula Animal', href: '/proyectos/formula-animal/', label: 'Ver caso completo de Fórmula Animal', text: 'Un CRM personalizado conecta pedidos, logística, calidad, clientes y facturación en una plataforma con más de 15 módulos relacionados.' },
    related: [
      { href: '/servicios/desarrollo-crm/', label: 'Desarrollo de CRM personalizado' },
      { href: '/soluciones/reemplazar-excel/', label: 'Cuándo reemplazar Excel' },
      { href: '/soluciones/digitalizar-pedidos/', label: 'Cómo digitalizar pedidos' },
    ],
    ctaTitle: '¿Tu operación ya necesita una herramienta propia?',
    ctaText: 'Cuéntanos cómo trabaja hoy tu equipo. Revisamos el proceso y te mostramos qué conviene digitalizar primero, sin compromiso.',
    ctaLabel: 'Solicitar diagnóstico gratuito',
    whatsappMessage: 'Hola, estoy interesado en desarrollar software a la medida para mi empresa y quisiera solicitar el diagnóstico inicial.',
  },
  'desarrollo-crm': {
    kind: 'service',
    kicker: 'Clientes y operación conectados',
    h1: 'Desarrollo de CRM personalizado',
    lead: 'Creamos CRM que reúnen la relación con cada cliente, el seguimiento comercial y los procesos que ocurren después de una venta.',
    intro: [
      'Un CRM útil no es solamente una libreta de contactos. Debe ayudar a que ventas, servicio y operación compartan contexto: qué pidió el cliente, quién quedó responsable, qué compromiso sigue, qué documentos existen y en qué estado se encuentra cada caso.',
      'Cuando la empresa tiene un proceso comercial propio, un CRM genérico puede terminar rodeado de hojas de cálculo, campos sin uso y conversaciones externas. Diseñamos la solución desde el recorrido real del cliente para que registrar información aporte claridad en lugar de convertirse en otra carga administrativa.',
    ],
    problemsTitle: 'Problemas que un CRM personalizado puede ordenar',
    problemsIntro: 'La necesidad suele aparecer cuando el conocimiento comercial está fragmentado y la continuidad depende de que una persona recuerde cada conversación.',
    problems: [
      { title: 'Contactos sin contexto', text: 'Hay nombres y teléfonos, pero no una historia comprensible de solicitudes, cotizaciones, acuerdos, compras y tareas pendientes.' },
      { title: 'Seguimientos que se pierden', text: 'Las próximas acciones quedan en agendas personales o chats. Si cambia el responsable, recuperar el estado de la oportunidad toma demasiado tiempo.' },
      { title: 'Ventas separadas de la entrega', text: 'El equipo comercial promete y registra información que luego debe copiarse para producción, logística, soporte o facturación.' },
      { title: 'Reportes preparados a mano', text: 'Conocer oportunidades abiertas, tiempos de respuesta o cargas de trabajo exige consolidar archivos y depende de criterios diferentes entre personas.' },
      { title: 'Un CRM estándar difícil de adoptar', text: 'La herramienta incluye demasiados pasos ajenos al negocio y omite controles esenciales, por lo que el equipo vuelve a sus métodos anteriores.' },
    ],
    audienceTitle: 'Empresas que obtienen más valor de un CRM propio',
    audienceIntro: 'La personalización es pertinente cuando la relación comercial continúa dentro de una operación con reglas, documentos o áreas específicas.',
    audience: [
      { title: 'Ventas consultivas', text: 'Equipos que necesitan comprender necesidades, preparar propuestas, coordinar varias conversaciones y conservar decisiones antes de cerrar.' },
      { title: 'Negocios con pedidos complejos', text: 'Empresas donde una venta contiene productos configurables, condiciones de entrega, aprobaciones o información técnica que debe viajar con el pedido.' },
      { title: 'Servicios con atención recurrente', text: 'Organizaciones que administran renovaciones, solicitudes, visitas, casos o acompañamientos y necesitan una visión histórica de cada cliente.' },
    ],
    solutionsTitle: 'Capacidades que se diseñan según el recorrido del cliente',
    solutionsIntro: 'No todas las empresas necesitan el mismo embudo. Seleccionamos los módulos que ayudan a avanzar y a transferir información sin perder contexto.',
    solutions: [
      { title: 'Ficha integral del cliente', text: 'Reúne datos de contacto, empresas relacionadas, conversaciones, documentos, compras y actividad reciente en una vista coherente.' },
      { title: 'Oportunidades y etapas propias', text: 'Representa el proceso comercial real, define responsables y permite conocer por qué una oportunidad avanza, se detiene o se descarta.' },
      { title: 'Tareas, recordatorios y alertas', text: 'Convierte compromisos en acciones visibles y avisa cuando una respuesta, documento o aprobación supera el tiempo esperado.' },
      { title: 'Pedidos y operación posterior', text: 'Traslada la información acordada hacia preparación, logística, calidad o facturación sin comenzar de nuevo en cada área.' },
      { title: 'Indicadores accionables', text: 'Muestra carga, seguimiento, estados y tiempos con filtros que ayudan a dirigir el trabajo, no solamente a producir informes.' },
    ],
    benefitsTitle: 'Qué cambia cuando todo el equipo comparte contexto',
    benefits: [
      { title: 'Continuidad comercial', text: 'Cualquier responsable autorizado puede retomar una conversación entendiendo lo ocurrido y el siguiente paso acordado.' },
      { title: 'Mejor coordinación', text: 'Ventas y operación trabajan sobre los mismos datos, reduciendo preguntas repetidas y errores durante la transferencia.' },
      { title: 'Seguimiento verificable', text: 'Las tareas, fechas y cambios quedan asociados al cliente o al pedido para evitar compromisos invisibles.' },
      { title: 'Decisiones con información reciente', text: 'El estado se actualiza durante el trabajo y alimenta vistas que muestran dónde intervenir sin esperar un consolidado mensual.' },
    ],
    processTitle: 'Cómo convertimos el recorrido comercial en un CRM',
    processIntro: 'Empezamos por las decisiones y entregas entre áreas. La interfaz aparece después de entender qué información debe acompañar cada paso.',
    process: [
      { title: 'Recorrer casos reales', text: 'Revisamos ejemplos recientes para entender canales, excepciones, documentos y criterios que usa el equipo.' },
      { title: 'Definir etapas y responsabilidades', text: 'Acordamos qué significa cada estado, quién puede cambiarlo y qué dato permite continuar.' },
      { title: 'Prototipar las vistas clave', text: 'Diseñamos la ficha del cliente, las oportunidades y el trabajo diario antes de construir la lógica completa.' },
      { title: 'Desarrollar un núcleo útil', text: 'Implementamos primero el flujo que produce continuidad y dejamos capacidades secundarias para entregas posteriores.' },
      { title: 'Preparar datos y adopción', text: 'Revisamos la información existente, los permisos y la forma de acompañar a quienes usarán el CRM.' },
      { title: 'Medir y evolucionar', text: 'Observamos qué campos y alertas ayudan, eliminamos fricción y priorizamos integraciones según el uso real.' },
    ],
    faqs: [
      { title: '¿En qué se diferencia de un CRM listo para usar?', text: 'Un CRM personalizado puede representar etapas, permisos y vínculos con la operación que son propios de la empresa. Antes de recomendarlo verificamos si una plataforma existente puede configurarse de forma suficiente.' },
      { title: '¿Se puede importar la información actual?', text: 'Normalmente sí, después de revisar formato, duplicados y calidad. Definimos qué historial aporta valor y cómo validarlo para no trasladar desorden al sistema nuevo.' },
      { title: '¿Puede conectarse con WhatsApp o correo?', text: 'La viabilidad depende de los servicios, cuentas y APIs autorizadas. Analizamos qué información debe registrarse, qué acciones pueden automatizarse y qué interacción seguirá necesitando criterio humano.' },
      { title: '¿También puede gestionar pedidos?', text: 'Sí, cuando el pedido nace de la relación comercial. Puede conservar productos, condiciones, responsables y estados, y entregar los datos necesarios a logística, calidad o facturación.' },
      { title: '¿Cómo evitan que el equipo deje de usarlo?', text: 'Incluimos a usuarios reales durante el diagnóstico y el prototipo, reducimos campos que no producen valor y acompañamos la implementación. La adopción se diseña; no se espera para el final.' },
    ],
    caseStudy: { name: 'Fórmula Animal', href: '/proyectos/formula-animal/', label: 'Conocer el CRM de Fórmula Animal', text: 'El caso muestra un CRM que no termina en la venta: conecta la captura del pedido con logística, calidad y facturación.' },
    related: [
      { href: '/servicios/software-a-la-medida/', label: 'Software a la medida' },
      { href: '/soluciones/digitalizar-pedidos/', label: 'Digitalización de pedidos' },
      { href: '/soluciones/reemplazar-excel/', label: 'Reemplazar hojas de cálculo' },
    ],
    ctaTitle: '¿Tu equipo comercial necesita más contexto y menos tareas manuales?',
    ctaText: 'Analizamos cómo gestionan hoy clientes, oportunidades y pedidos para proponer un punto de partida alcanzable.',
    ctaLabel: 'Solicitar diagnóstico de CRM',
    whatsappMessage: 'Hola, estoy interesado en desarrollar un CRM para mi empresa y quisiera solicitar el diagnóstico inicial.',
  },
  'automatizacion-de-procesos': {
    kind: 'service',
    kicker: 'Menos tareas repetitivas',
    h1: 'Automatización de procesos empresariales',
    lead: 'Conectamos herramientas, datos y decisiones para que los procesos avancen con menos digitación, menos esperas y mayor control.',
    intro: [
      'Automatizar no significa ejecutar todo sin personas. Significa identificar tareas predecibles que una máquina puede realizar de forma consistente y reservar el criterio humano para excepciones, decisiones y relaciones que realmente lo requieren.',
      'Antes de proponer integraciones o inteligencia artificial, observamos el recorrido completo. Una automatización aislada puede trasladar el problema a otra etapa; una bien diseñada entiende qué evento la inicia, qué datos necesita, cómo informa el resultado y qué ocurre cuando algo no cumple las condiciones previstas.',
    ],
    problemsTitle: 'Fricciones que suelen indicar una oportunidad de automatización',
    problemsIntro: 'Los mejores candidatos son pasos repetidos, basados en reglas y con entradas relativamente estables. También revisamos el costo de los errores y la necesidad de supervisión.',
    problems: [
      { title: 'Copiar datos entre herramientas', text: 'Una persona recibe información en un canal, la vuelve a digitar en otro sistema y repite el proceso para mantener varios registros actualizados.' },
      { title: 'Recordatorios que dependen de memoria', text: 'Seguimientos, vencimientos o confirmaciones se realizan cuando alguien los recuerda, no cuando la condición del proceso los exige.' },
      { title: 'Documentos preparados de forma repetitiva', text: 'El equipo toma los mismos datos para generar formatos, mensajes o reportes con pequeñas variaciones que consumen tiempo y permiten errores.' },
      { title: 'Sistemas que no se comunican', text: 'Una acción se completa en una plataforma, pero otras áreas no reciben el cambio y deben consultar o actualizar manualmente sus herramientas.' },
      { title: 'Demoras entre un evento y una respuesta', text: 'La información existe, pero nadie sabe de inmediato que debe actuar. El trabajo queda detenido hasta la siguiente revisión manual.' },
    ],
    audienceTitle: 'Procesos donde la automatización suele aportar valor',
    audienceIntro: 'No es necesario ser una empresa grande. Una tarea breve, repetida muchas veces y vinculada a ingresos o servicio puede justificar una mejora concreta.',
    audience: [
      { title: 'Equipos administrativos', text: 'Áreas que consolidan información, verifican condiciones, crean documentos y distribuyen resultados entre responsables.' },
      { title: 'Operaciones con varias plataformas', text: 'Negocios que necesitan sincronizar clientes, pedidos, inventario, pagos o estados entre herramientas con APIs disponibles.' },
      { title: 'Servicios con tiempos de respuesta críticos', text: 'Procesos donde una alerta, asignación o confirmación oportuna evita retrasos y ayuda a cumplir compromisos con clientes.' },
    ],
    solutionsTitle: 'Formas de automatizar sin perder visibilidad',
    solutionsIntro: 'Elegimos el mecanismo según la estabilidad del proceso, los accesos disponibles y el nivel de riesgo. No todas las tareas necesitan inteligencia artificial.',
    solutions: [
      { title: 'Flujos de trabajo automáticos', text: 'Ejecutan acciones cuando ocurre un evento: asignar una tarea, validar un dato, actualizar un estado o avisar a un responsable.' },
      { title: 'Integraciones mediante APIs', text: 'Permiten que dos sistemas intercambien información de forma controlada, con registros que facilitan detectar y corregir fallos.' },
      { title: 'Generación de documentos y comunicaciones', text: 'Componen salidas a partir de datos aprobados, conservando plantillas, responsables y condiciones de envío.' },
      { title: 'Paneles y alertas operativas', text: 'Reúnen señales importantes y notifican desviaciones para que el equipo intervenga donde su criterio produce mayor valor.' },
      { title: 'Asistencia con inteligencia artificial', text: 'Puede clasificar, resumir o consultar información cuando existe una fuente definida y un punto claro de revisión humana.' },
    ],
    benefitsTitle: 'Beneficios que deben poder observarse en el proceso',
    benefits: [
      { title: 'Tiempo recuperado', text: 'El equipo reduce pasos mecánicos y puede dedicar más atención a clientes, decisiones y situaciones excepcionales.' },
      { title: 'Menos errores de transcripción', text: 'La información viaja entre etapas sin volver a escribirse, manteniendo validaciones y formatos consistentes.' },
      { title: 'Respuestas oportunas', text: 'Las acciones se activan por eventos y condiciones, no únicamente por revisiones periódicas o memoria individual.' },
      { title: 'Trazabilidad de cada ejecución', text: 'Los resultados, errores y reintentos quedan visibles para supervisar la automatización y corregir causas, no solo síntomas.' },
    ],
    processTitle: 'Cómo identificamos y construimos una automatización',
    processIntro: 'Priorizamos oportunidades viables y medibles. Automatizar un proceso confuso puede volverlo más rápido, pero no necesariamente mejor.',
    process: [
      { title: 'Observar el trabajo actual', text: 'Registramos disparadores, datos, decisiones, esperas, responsables y excepciones del proceso completo.' },
      { title: 'Evaluar impacto y riesgo', text: 'Comparamos frecuencia, tiempo, errores y criticidad para decidir qué paso conviene intervenir primero.' },
      { title: 'Diseñar controles', text: 'Definimos permisos, validaciones, registros y rutas de atención cuando la automatización no puede continuar.' },
      { title: 'Construir e integrar', text: 'Implementamos el flujo con las plataformas autorizadas y probamos escenarios normales y excepcionales.' },
      { title: 'Supervisar la salida', text: 'Durante la adopción revisamos ejecuciones reales, afinamos reglas y mantenemos la posibilidad de intervención humana.' },
      { title: 'Ampliar con evidencia', text: 'Solo extendemos la automatización cuando el primer flujo demuestra estabilidad y el equipo comprende su funcionamiento.' },
    ],
    faqs: [
      { title: '¿Qué proceso conviene automatizar primero?', text: 'Uno frecuente, basado en reglas, con datos disponibles y un resultado fácil de comprobar. También debe tener suficiente impacto para justificar la integración y un riesgo controlable si algo falla.' },
      { title: '¿Automatización siempre significa inteligencia artificial?', text: 'No. Muchas mejoras confiables se resuelven con reglas, APIs y validaciones convencionales. Usamos IA cuando la tarea requiere interpretar contenido y existe un mecanismo adecuado de revisión.' },
      { title: '¿Qué ocurre si una integración falla?', text: 'Diseñamos registros, alertas y rutas de recuperación de acuerdo con la importancia del proceso. Una automatización no debe ocultar errores ni dejar al equipo sin forma de intervenir.' },
      { title: '¿Pueden conectar las herramientas que ya utilizamos?', text: 'Revisamos si ofrecen APIs, webhooks u otros mecanismos autorizados, sus límites y costos. Con esa información definimos una integración sostenible y evitamos depender de accesos frágiles.' },
      { title: '¿Cómo se mide el resultado?', text: 'Acordamos señales como tiempo por caso, cantidad de pasos manuales, errores, demoras o cumplimiento. La métrica depende del problema y se compara con el flujo anterior.' },
    ],
    caseStudy: { name: 'Lia', href: '/proyectos/lia/', label: 'Ver el caso de Lia', text: 'Lia reúne consulta, análisis y ejecución asistida en una interfaz pensada para automatizar procesos sin perder supervisión.' },
    related: [
      { href: '/soluciones/automatizar-procesos/', label: 'Qué procesos manuales automatizar' },
      { href: '/servicios/software-a-la-medida/', label: 'Software a la medida' },
      { href: '/servicios/desarrollo-crm/', label: 'CRM personalizado' },
    ],
    ctaTitle: 'Identifica qué tareas puede dejar de repetir tu equipo',
    ctaText: 'Revisamos un proceso concreto, sus herramientas y sus excepciones para encontrar una primera automatización con sentido.',
    ctaLabel: 'Solicitar diagnóstico de automatización',
    whatsappMessage: 'Hola, quiero automatizar procesos en mi empresa y quisiera solicitar un diagnóstico inicial.',
  },
  'desarrollo-web': {
    kind: 'service',
    kicker: 'Presencia digital útil',
    h1: 'Desarrollo web para empresas',
    lead: 'Diseñamos sitios y aplicaciones web que explican con claridad lo que hace tu empresa, funcionan rápido y convierten el interés en una acción concreta.',
    intro: [
      'Una página empresarial no debería ser un folleto aislado. Es un punto de encuentro entre lo que una persona busca, la confianza que necesita para considerar una empresa y la acción que puede realizar: escribir, solicitar una evaluación, explorar un servicio o iniciar una cotización.',
      'Trabajamos la estructura, el contenido y la implementación como una sola experiencia. Así evitamos sitios visualmente atractivos que no explican la oferta, páginas lentas que pierden visitas y contenidos que dependen de animaciones o JavaScript para que buscadores y asistentes puedan entenderlos.',
    ],
    problemsTitle: 'Qué resolvemos en una presencia web empresarial',
    problemsIntro: 'La necesidad no siempre es “tener una web nueva”. Muchas veces consiste en ordenar el mensaje, reducir fricción o convertir una página existente en una herramienta comercial confiable.',
    problems: [
      { title: 'La empresa no se entiende rápido', text: 'El visitante encuentra frases generales, pero no logra identificar qué problema resuelven, para quién trabajan o cuál es el siguiente paso.' },
      { title: 'La página no genera conversaciones', text: 'Existe tráfico o se comparte el enlace, pero los servicios carecen de contexto, evidencia y llamados a la acción relacionados con la intención del visitante.' },
      { title: 'La experiencia móvil tiene fricción', text: 'Textos, botones, imágenes o formularios dificultan la consulta desde teléfonos, donde suele comenzar buena parte de la búsqueda comercial.' },
      { title: 'Actualizar contenido es difícil', text: 'Cada cambio exige rehacer secciones delicadas o depender de una estructura que ya no representa los servicios actuales.' },
      { title: 'El rendimiento limita la visibilidad', text: 'Imágenes pesadas, dependencias innecesarias o contenido tardío afectan la experiencia y reducen la calidad técnica del sitio.' },
    ],
    audienceTitle: 'Sitios web pensados para una necesidad concreta',
    audienceIntro: 'Definimos la solución según el recorrido que la empresa quiere facilitar, no por una cantidad fija de páginas o efectos.',
    audience: [
      { title: 'Empresas de servicios', text: 'Negocios que necesitan explicar capacidades, sectores, forma de trabajo y evidencia para convertir una búsqueda en una conversación calificada.' },
      { title: 'Catálogos y cotizadores', text: 'Empresas con productos configurables o portafolios que requieren filtros, información contextual y una transición clara hacia asesoría o compra.' },
      { title: 'Portales y aplicaciones', text: 'Equipos que necesitan ofrecer consultas, formularios, seguimiento o herramientas en línea conectadas con procesos internos.' },
    ],
    solutionsTitle: 'Qué puede incluir un proyecto de desarrollo web',
    solutionsIntro: 'Construimos solo lo que aporta al objetivo. El contenido principal queda disponible desde el HTML para conservar accesibilidad, rendimiento e indexación.',
    solutions: [
      { title: 'Arquitectura y contenido', text: 'Organizamos páginas y mensajes según preguntas reales del cliente, servicios específicos y relaciones internas comprensibles.' },
      { title: 'Diseño responsive', text: 'Creamos jerarquías, componentes y llamadas a la acción que mantienen claridad y facilidad de uso en distintos tamaños de pantalla.' },
      { title: 'Implementación rápida y accesible', text: 'Cuidamos HTML semántico, navegación por teclado, contraste, imágenes responsivas y una carga inicial contenida.' },
      { title: 'SEO técnico de base', text: 'Configuramos metadata única, canonical, sitemap, robots, datos estructurados pertinentes y renderizado rastreable.' },
      { title: 'Conexión con la operación', text: 'Integramos formularios, WhatsApp, catálogos o servicios permitidos para que la oportunidad no termine en una bandeja sin seguimiento.' },
    ],
    benefitsTitle: 'Una web que trabaja como parte del negocio',
    benefits: [
      { title: 'Propuesta comprensible', text: 'La persona reconoce pronto si el servicio responde a su situación y puede profundizar sin atravesar lenguaje genérico.' },
      { title: 'Mejor punto de llegada', text: 'Campañas, recomendaciones y búsquedas encuentran páginas específicas con contexto y una acción coherente.' },
      { title: 'Base preparada para crecer', text: 'La estructura permite añadir servicios, casos y contenidos manteniendo navegación, metadata y enlazado consistentes.' },
      { title: 'Experiencia veloz', text: 'Una implementación sobria reduce esperas y mantiene el foco en la información que ayuda a decidir.' },
    ],
    processTitle: 'Cómo construimos una experiencia web empresarial',
    processIntro: 'Alineamos mensaje, recorrido y tecnología desde el inicio para no tratar el contenido como un relleno posterior al diseño.',
    process: [
      { title: 'Definir objetivo y audiencias', text: 'Acordamos qué debe entender cada visitante y qué acción representa valor para el negocio.' },
      { title: 'Ordenar la arquitectura', text: 'Convertimos servicios, problemas, preguntas y evidencia en rutas con una función clara.' },
      { title: 'Escribir y prototipar', text: 'Validamos jerarquía, contenido y navegación antes de dedicar esfuerzo a detalles finales.' },
      { title: 'Desarrollar componentes', text: 'Implementamos una interfaz responsive, accesible y coherente con la identidad visual existente.' },
      { title: 'Verificar calidad', text: 'Probamos enlaces, metadata, schema, imágenes, comportamiento móvil y rutas importantes de conversión.' },
      { title: 'Publicar y acompañar', text: 'Revisamos la versión desplegada y dejamos una base que pueda actualizarse sin degradar el rendimiento.' },
    ],
    faqs: [
      { title: '¿Desarrollan sitios nuevos y también mejoran sitios existentes?', text: 'Sí. Primero revisamos si la arquitectura y la base técnica actual pueden conservarse. Cuando es viable, reorganizar contenido y componentes suele ser más responsable que reemplazar todo.' },
      { title: '¿El sitio quedará preparado para SEO?', text: 'Incluimos fundamentos técnicos y una estructura rastreable. El posicionamiento también depende de contenido, competencia, autoridad y mantenimiento; por eso evitamos prometer resultados automáticos.' },
      { title: '¿Cómo mantienen un buen rendimiento?', text: 'Reducimos dependencias, optimizamos recursos, servimos tamaños de imagen adecuados y evitamos animaciones que bloqueen el contenido. Después verificamos la compilación y el comportamiento real.' },
      { title: '¿Pueden integrar WhatsApp o un formulario?', text: 'Sí. Diseñamos el contacto según la página y el contexto para que el mensaje inicial ayude a continuar la conversación. También consideramos privacidad, validación y destino de la información.' },
      { title: '¿La página funciona en teléfonos?', text: 'El diseño y la implementación se prueban de forma responsive. Priorizamos lectura, tamaño de controles, orden del contenido y estabilidad visual, no solo que los elementos “quepan”.' },
    ],
    caseStudy: { name: 'Nativhaus', href: '/proyectos/native-haus/', label: 'Ver la experiencia web de Nativhaus', text: 'Nativhaus conecta catálogo, exploración visual, cotización y contacto contextual en una experiencia comercial responsive.' },
    related: [
      { href: '/servicios/seo-local/', label: 'SEO local para empresas' },
      { href: '/soluciones/mejorar-presencia-digital/', label: 'Mejorar presencia digital' },
      { href: '/servicios/software-a-la-medida/', label: 'Aplicaciones web a la medida' },
    ],
    ctaTitle: '¿Tu página explica y convierte lo que tu empresa hace bien?',
    ctaText: 'Revisamos el sitio, el mensaje y el recorrido actual para identificar mejoras de contenido, experiencia y tecnología.',
    ctaLabel: 'Solicitar diagnóstico web',
    whatsappMessage: 'Hola, quiero mejorar o desarrollar la página web de mi empresa y quisiera solicitar un diagnóstico inicial.',
  },
  'seo-local': {
    kind: 'service',
    kicker: 'Visibilidad en tu zona',
    h1: 'SEO local para empresas en Colombia',
    lead: 'Mejoramos la forma en que tu negocio aparece y se entiende en Google, Maps y búsquedas relacionadas con tus servicios y áreas de atención.',
    intro: [
      'El SEO local ayuda a una persona cercana —o interesada en una zona específica— a encontrar una empresa relevante, verificar que ofrece lo que necesita y elegir una vía de contacto. Para lograrlo deben coincidir la información pública del negocio, su sitio web y las señales de confianza disponibles.',
      'No se trata de repetir nombres de ciudades ni crear páginas casi idénticas. Trabajamos sobre datos verificables, categorías, servicios, contenido útil, consistencia de contacto y fundamentos técnicos. La estrategia se adapta a la presencia real de la empresa y evita inventar ubicaciones, reseñas o cobertura.',
    ],
    problemsTitle: 'Por qué un negocio puede perder visibilidad local',
    problemsIntro: 'La ausencia en resultados rara vez depende de una sola etiqueta. Revisamos la entidad completa y la experiencia que encuentra una persona después de hacer clic.',
    problems: [
      { title: 'Perfil incompleto o inconsistente', text: 'El nombre, teléfono, horarios, categorías o servicios no coinciden entre Google Business, el sitio y otras referencias públicas.' },
      { title: 'El sitio no explica dónde y cómo atiende', text: 'Las páginas describen la empresa de forma general, pero no aclaran servicios, áreas reales, proceso de contacto ni información útil para decidir.' },
      { title: 'Problemas técnicos de rastreo', text: 'Canonical incorrecto, rutas duplicadas, contenido cargado tarde o un sitemap desactualizado dificultan que el buscador interprete la estructura.' },
      { title: 'Poca evidencia de confianza', text: 'Faltan casos, información empresarial y señales externas verificables que ayuden a diferenciar el negocio dentro de su categoría.' },
      { title: 'Experiencia móvil deficiente', text: 'Quien busca desde el teléfono encuentra una página lenta, difícil de leer o sin un contacto visible relacionado con su necesidad.' },
    ],
    audienceTitle: 'Negocios que pueden aprovechar una estrategia local',
    audienceIntro: 'El enfoque funciona para empresas con atención física, visitas, entregas o servicios concentrados en zonas donde realmente pueden operar.',
    audience: [
      { title: 'Empresas con sede o punto de atención', text: 'Negocios que reciben clientes y necesitan mantener datos, categorías, horarios, servicios y ubicación consistentes.' },
      { title: 'Servicios que se desplazan', text: 'Equipos que visitan al cliente dentro de un área definida y deben comunicar cobertura sin fingir oficinas que no existen.' },
      { title: 'Marcas con varias ubicaciones reales', text: 'Empresas que requieren una estructura clara por sede, contenidos propios y un control consistente de la información de cada perfil.' },
    ],
    solutionsTitle: 'Qué revisamos y optimizamos',
    solutionsIntro: 'Priorizamos los elementos que la empresa puede demostrar y mantener. El diagnóstico determina si el primer trabajo está en Google Business, el sitio o la consistencia de la entidad.',
    solutions: [
      { title: 'Google Business Profile', text: 'Revisamos categorías, servicios, descripción, horarios, enlaces, fotografías y coherencia con la información publicada en el sitio.' },
      { title: 'Páginas de servicio', text: 'Creamos o mejoramos contenidos que responden preguntas reales, explican el alcance y conectan la búsqueda con una acción específica.' },
      { title: 'SEO técnico local', text: 'Validamos indexación, canonical, sitemap, metadatos, rendimiento móvil, enlaces internos y datos estructurados apropiados.' },
      { title: 'Consistencia de negocio', text: 'Identificamos diferencias en nombre, dirección cuando aplica, teléfono y referencias importantes que pueden generar confusión.' },
      { title: 'Medición y prioridades', text: 'Definimos consultas, páginas y conversiones que merece la pena observar para evaluar cambios y evitar métricas aisladas.' },
    ],
    benefitsTitle: 'Una presencia local más clara y sostenible',
    benefits: [
      { title: 'Mejor comprensión del negocio', text: 'Buscadores y personas encuentran información coherente sobre servicios, cobertura y formas de contacto.' },
      { title: 'Visitas con mayor intención', text: 'Las páginas responden a necesidades específicas y ofrecen un siguiente paso relacionado con lo que la persona buscó.' },
      { title: 'Menos inconsistencias', text: 'La empresa cuenta con criterios claros para mantener sus datos públicos cuando cambian horarios, servicios o canales.' },
      { title: 'Base para mejorar con evidencia', text: 'El seguimiento permite distinguir entre visibilidad, interacción y conversaciones reales, sin prometer posiciones garantizadas.' },
    ],
    processTitle: 'Cómo abordamos el SEO local',
    processIntro: 'Trabajamos desde la situación actual y la presencia real de la empresa. No creamos ubicaciones artificiales ni contenidos intercambiables entre ciudades.',
    process: [
      { title: 'Diagnóstico de visibilidad', text: 'Revisamos perfil, sitio, indexación, consultas relevantes y consistencia de la información pública disponible.' },
      { title: 'Definición de prioridades', text: 'Ordenamos correcciones técnicas, contenido y mejoras del perfil según su impacto y viabilidad.' },
      { title: 'Optimización de entidad', text: 'Alineamos datos, categorías, servicios y señales verificables entre los activos controlados por la empresa.' },
      { title: 'Mejora del sitio', text: 'Fortalecemos páginas, enlazado, metadata, rendimiento y llamadas a la acción relacionadas con la intención local.' },
      { title: 'Publicación y control', text: 'Verificamos que buscadores puedan rastrear los cambios y que la información sea correcta en distintos dispositivos.' },
      { title: 'Seguimiento', text: 'Observamos visibilidad, interacciones y contactos para decidir qué contenido o señal conviene reforzar después.' },
    ],
    faqs: [
      { title: '¿Pueden garantizar la primera posición en Google?', text: 'No. Los resultados dependen de competencia, ubicación, relevancia, autoridad y cambios del buscador. Sí podemos mejorar la calidad técnica, la coherencia y la utilidad de la presencia digital.' },
      { title: '¿Necesito una dirección pública?', text: 'Depende del modelo de atención y las reglas de Google Business Profile. No recomendamos mostrar ni crear direcciones que no correspondan a una presencia legítima.' },
      { title: '¿Crearán una página para cada ciudad?', text: 'Solo cuando existe una razón empresarial y contenido realmente distinto. Las páginas que cambian únicamente el nombre de la ciudad pueden resultar poco útiles y generar riesgo de contenido tipo doorway.' },
      { title: '¿SEO local incluye mejorar la página web?', text: 'Sí, cuando el sitio limita la comprensión, la indexación o la conversión. El perfil y la web deben apoyarse mutuamente con información consistente y páginas relevantes.' },
      { title: '¿Cuándo se ven resultados?', text: 'No existe un plazo universal. Corregir datos puede reflejarse antes que construir autoridad o competir por búsquedas exigentes. Definimos indicadores intermedios y revisamos avances sin inventar garantías.' },
    ],
    caseStudy: { name: 'Nativhaus', href: '/proyectos/native-haus/', label: 'Explorar el caso Nativhaus', text: 'La experiencia web de Nativhaus organiza productos y rutas de contacto para convertir el interés digital en una conversación contextual.' },
    related: [
      { href: '/servicios/desarrollo-web/', label: 'Desarrollo web para empresas' },
      { href: '/soluciones/mejorar-presencia-digital/', label: 'Mejorar presencia digital' },
      { href: '/servicios/software-a-la-medida/', label: 'Soluciones digitales a la medida' },
    ],
    ctaTitle: 'Descubre qué limita la visibilidad local de tu negocio',
    ctaText: 'Revisamos Google, Maps, el sitio web y la consistencia de la información para priorizar mejoras reales.',
    ctaLabel: 'Solicitar diagnóstico de presencia digital',
    whatsappMessage: 'Hola, quiero mejorar la presencia de mi negocio en Google y quisiera solicitar el diagnóstico digital.',
  },
  'reemplazar-excel': {
    kind: 'solution',
    kicker: 'Información bajo control',
    h1: '¿Tu empresa todavía depende de Excel?',
    lead: 'Excel es una herramienta valiosa, pero deja de ser suficiente cuando varias personas, reglas y decisiones dependen del mismo archivo para operar.',
    intro: [
      'Muchas empresas empiezan organizando clientes, inventarios, pedidos o pagos en hojas de cálculo. Es una solución flexible y conocida. El problema aparece cuando el archivo se convierte en el centro de una operación que necesita permisos, colaboración simultánea, historial y conexiones con otras áreas.',
      'Reemplazar Excel no significa prohibirlo ni convertir cada tabla en un sistema. Analizamos qué hojas siguen siendo útiles y cuáles concentran riesgos, trabajo repetido o información crítica. El objetivo es mover el proceso adecuado a una herramienta que conserve la flexibilidad necesaria y añada control donde hoy falta.',
    ],
    problemsTitle: 'Qué ocurre cuando una hoja se convierte en sistema',
    problemsIntro: 'El límite no depende de una cantidad exacta de filas. Se reconoce por la dificultad para confiar, colaborar y reconstruir lo que pasó.',
    problems: [
      { title: 'Versiones diferentes del mismo archivo', text: 'Copias enviadas por correo o chat contienen cambios incompatibles y nadie puede asegurar cuál representa el estado vigente.' },
      { title: 'Errores difíciles de detectar', text: 'Una fórmula modificada, una fila movida o un dato escrito con otro formato cambia resultados sin dejar una alerta comprensible.' },
      { title: 'Información duplicada', text: 'Clientes, productos o pedidos se vuelven a registrar en varios libros, lo que exige comparar y corregir diferencias constantemente.' },
      { title: 'Colaboración limitada', text: 'Varias personas necesitan editar, aprobar o consultar, pero no todas deberían cambiar las mismas columnas ni acceder a todos los datos.' },
      { title: 'Pérdida de trazabilidad', text: 'Es difícil saber quién cambió un estado, por qué lo hizo, qué dato existía antes y qué decisión se tomó con esa información.' },
    ],
    audienceTitle: 'Cuándo Excel deja de ser suficiente',
    audienceIntro: 'La señal más clara es que el equipo trabaja alrededor del archivo: crea controles paralelos, pide confirmaciones o evita tocar datos por miedo a dañarlos.',
    audience: [
      { title: 'El archivo coordina varias áreas', text: 'Ventas, operación, inventario o administración necesitan actuar sobre el mismo registro y cada cambio afecta el trabajo de otros.' },
      { title: 'El proceso exige permisos y aprobaciones', text: 'No todas las personas pueden editar todo, ciertos cambios necesitan validación y hay información que debe conservar un historial.' },
      { title: 'Preparar reportes consume demasiado tiempo', text: 'Los datos existen, pero deben limpiarse, combinarse y reinterpretarse cada vez que alguien necesita tomar una decisión.' },
    ],
    solutionsTitle: 'Cómo puede reemplazarse un proceso basado en hojas de cálculo',
    solutionsIntro: 'El nuevo sistema organiza entidades y relaciones: un cliente puede tener pedidos; un pedido, estados; y cada estado, responsables y fechas verificables.',
    solutions: [
      { title: 'Base de datos centralizada', text: 'Mantiene una versión compartida de clientes, productos, movimientos y documentos, con búsquedas y relaciones consistentes.' },
      { title: 'Accesos por rol', text: 'Cada persona consulta o modifica lo que necesita, mientras las acciones sensibles quedan restringidas y registradas.' },
      { title: 'Flujos y validaciones', text: 'El sistema comprueba datos, guía el orden de trabajo y evita avanzar cuando falta una condición importante.' },
      { title: 'Historial de actividad', text: 'Los cambios relevantes quedan asociados a una fecha, un responsable y un contexto para facilitar seguimiento y auditoría.' },
      { title: 'Reportes disponibles durante la operación', text: 'Las vistas se alimentan de los datos actuales y reducen la necesidad de preparar un consolidado desde cero.' },
    ],
    benefitsTitle: 'Qué mejora al centralizar la operación',
    benefits: [
      { title: 'Confianza en los datos', text: 'El equipo consulta una fuente común y reduce discusiones sobre versiones, formatos y cifras incompatibles.' },
      { title: 'Menos correcciones', text: 'Las reglas se aplican al registrar información y los errores pueden detectarse antes de afectar las etapas siguientes.' },
      { title: 'Responsabilidades claras', text: 'Los estados y permisos hacen visible quién debe intervenir y qué acción está pendiente.' },
      { title: 'Crecimiento sin multiplicar archivos', text: 'Más clientes, pedidos o colaboradores no requieren crear una copia nueva del proceso para mantenerlo funcionando.' },
    ],
    processTitle: 'Una transición gradual, no un cambio a ciegas',
    processIntro: 'Protegemos la continuidad del negocio y evitamos trasladar hojas desordenadas sin comprender qué representa cada dato.',
    process: [
      { title: 'Inventariar archivos y usos', text: 'Identificamos quién usa cada hoja, qué decisiones soporta y dónde se originan sus datos.' },
      { title: 'Elegir el proceso prioritario', text: 'Empezamos por el punto con mayor impacto, riesgo o repetición y dejamos fuera lo que todavía funciona bien.' },
      { title: 'Diseñar datos y flujo', text: 'Definimos entidades, permisos, validaciones, estados y reportes necesarios para la primera versión.' },
      { title: 'Preparar la migración', text: 'Revisamos duplicados, formatos y calidad para importar solo información comprensible y verificable.' },
      { title: 'Implementar con usuarios reales', text: 'Probamos escenarios cotidianos, ajustamos fricción y acompañamos el paso desde la hoja hacia el sistema.' },
      { title: 'Retirar controles paralelos', text: 'Cuando la nueva fuente es confiable, acordamos qué archivos dejan de editarse para evitar volver a duplicar la operación.' },
    ],
    faqs: [
      { title: '¿Hay que reemplazar todas las hojas de cálculo?', text: 'No. Excel sigue siendo útil para análisis y tareas individuales. Intervenimos las hojas que actúan como sistemas compartidos y generan riesgo, duplicación o trabajo operativo innecesario.' },
      { title: '¿Se pueden conservar los datos históricos?', text: 'Sí, si aportan valor y tienen calidad suficiente. Primero se revisan estructura, formatos y duplicados; después se define qué importar y qué mantener como archivo de consulta.' },
      { title: '¿Cómo sabemos si necesitamos un sistema personalizado?', text: 'El diagnóstico compara complejidad, reglas propias, herramientas existentes y costo del problema. A veces basta con reorganizar el proceso o configurar una solución disponible.' },
      { title: '¿El equipo podrá descargar información?', text: 'Puede contemplarse exportación y reportes según los permisos y necesidades reales. La meta no es encerrar los datos, sino administrarlos con mayor control.' },
      { title: '¿Se puede empezar por un solo módulo?', text: 'Sí. Una primera etapa acotada reduce riesgo, permite aprender con el equipo y prepara una base para integrar otros procesos después.' },
    ],
    caseStudy: { name: 'Fórmula Animal', href: '/proyectos/formula-animal/', label: 'Ver cómo Fórmula Animal centralizó su operación', text: 'El CRM reúne información comercial, pedidos, logística, calidad y facturación que necesita conservar trazabilidad a lo largo de varias áreas.' },
    related: [
      { href: '/servicios/software-a-la-medida/', label: 'Software a la medida para empresas' },
      { href: '/servicios/desarrollo-crm/', label: 'Desarrollo de CRM personalizado' },
      { href: '/soluciones/digitalizar-pedidos/', label: 'Digitalizar la gestión de pedidos' },
    ],
    ctaTitle: 'Averigua qué hojas conviene convertir en un sistema',
    ctaText: 'Muéstranos cómo circula hoy la información y te ayudamos a identificar el primer proceso que merece centralizarse.',
    ctaLabel: 'Analizar mi proceso',
    whatsappMessage: 'Hola, mi empresa depende de archivos de Excel para operar y quiero analizar cómo reemplazarlos por un sistema.',
  },
  'digitalizar-pedidos': {
    kind: 'solution',
    kicker: 'Del mensaje a la operación',
    h1: 'Digitaliza los pedidos de tu empresa',
    lead: 'Convierte pedidos recibidos por WhatsApp, llamadas y archivos en un flujo ordenado que conecta clientes, productos, responsables y estados.',
    intro: [
      'WhatsApp es un canal cómodo para conversar, pero no fue diseñado para controlar una operación completa. Cuando allí se mezclan referencias, cantidades, cambios, comprobantes y direcciones, el equipo debe interpretar mensajes y volver a registrar datos antes de empezar a trabajar.',
      'Digitalizar pedidos no significa eliminar el canal que prefieren los clientes. Significa crear una fuente operativa donde la solicitud queda estructurada, validada y disponible para las áreas que deben prepararla, entregarla, facturarla o responder preguntas sobre su estado.',
    ],
    problemsTitle: 'Qué se pierde cuando cada pedido vive en una conversación',
    problemsIntro: 'La fricción aumenta con el volumen: más mensajes, más personas y más excepciones hacen difícil mantener una imagen completa de la operación.',
    problems: [
      { title: 'Datos incompletos', text: 'Faltan cantidades, referencias, dirección o condiciones y el equipo debe volver a preguntar antes de registrar la solicitud.' },
      { title: 'Cambios sin una versión final', text: 'El cliente modifica el pedido en mensajes separados y no queda una vista consolidada de lo que realmente debe prepararse.' },
      { title: 'Doble digitación', text: 'La información del chat se copia a hojas, inventario, facturación y guías, multiplicando tiempo y oportunidades de error.' },
      { title: 'Estados difíciles de consultar', text: 'Responder si un pedido está confirmado, preparado o despachado exige buscar conversaciones o preguntar a otra persona.' },
      { title: 'Poca capacidad de análisis', text: 'Los datos quedan en texto libre y resulta difícil conocer tiempos, productos solicitados, novedades o carga por responsable.' },
    ],
    audienceTitle: 'Operaciones que necesitan un flujo de pedidos compartido',
    audienceIntro: 'La digitalización aporta más valor cuando varias áreas participan o cuando una omisión inicial produce correcciones costosas después.',
    audience: [
      { title: 'Distribución y comercio', text: 'Negocios que reciben referencias y cantidades por varios canales y deben coordinar disponibilidad, preparación y entrega.' },
      { title: 'Productos personalizados', text: 'Empresas donde cada pedido incluye medidas, fórmulas, opciones o documentos que deben mantenerse vinculados.' },
      { title: 'Servicios con programación', text: 'Equipos que convierten una solicitud en visita, reserva o trabajo asignado y necesitan coordinar fecha, responsable y estado.' },
    ],
    solutionsTitle: 'Un pedido estructurado desde el inicio hasta el cierre',
    solutionsIntro: 'El sistema se adapta a las reglas del negocio y puede conservar WhatsApp como puerta de entrada, mientras la gestión ocurre en un entorno trazable.',
    solutions: [
      { title: 'Captura guiada', text: 'Solicita datos esenciales, valida formatos y relaciona al cliente con productos, condiciones y documentos.' },
      { title: 'Estados y responsables', text: 'Cada pedido avanza por etapas definidas y muestra quién debe actuar y qué condición falta.' },
      { title: 'Conexión con inventario', text: 'Consulta disponibilidad o reserva unidades cuando el alcance y las herramientas actuales permiten integrarlo.' },
      { title: 'Notificaciones contextuales', text: 'Informa cambios relevantes a responsables o clientes sin obligarlos a preguntar continuamente por el estado.' },
      { title: 'Historial y reportes', text: 'Conserva novedades y tiempos para entender cuellos de botella, demanda y causas frecuentes de corrección.' },
    ],
    benefitsTitle: 'Qué gana el negocio con un flujo compartido',
    benefits: [
      { title: 'Menos pedidos ambiguos', text: 'La información requerida se confirma antes de pasar a preparación o prestación del servicio.' },
      { title: 'Continuidad entre áreas', text: 'Cada equipo recibe los datos que necesita sin reconstruir la solicitud desde una conversación.' },
      { title: 'Respuestas más rápidas', text: 'El estado y las novedades están disponibles para atender al cliente sin interrumpir a toda la operación.' },
      { title: 'Información para mejorar', text: 'Los pedidos estructurados permiten observar tiempos, errores y patrones que antes quedaban ocultos en mensajes.' },
    ],
    processTitle: 'Cómo diseñamos la digitalización de pedidos',
    processIntro: 'Partimos de pedidos reales y de sus excepciones para no crear un formulario que funcione solo en el escenario ideal.',
    process: [
      { title: 'Revisar canales y ejemplos', text: 'Analizamos cómo llegan las solicitudes, qué suele faltar y qué cambios aparecen después.' },
      { title: 'Mapear el recorrido', text: 'Identificamos áreas, decisiones, documentos y momentos donde un dato cambia o debe validarse.' },
      { title: 'Definir el registro central', text: 'Diseñamos la estructura del pedido, sus estados, permisos y relaciones con cliente, producto o servicio.' },
      { title: 'Construir el flujo prioritario', text: 'Implementamos desde la captura hasta un resultado útil y medible antes de añadir integraciones secundarias.' },
      { title: 'Probar con operación real', text: 'Validamos pedidos normales, urgentes, incompletos y modificados con las personas que los gestionan.' },
      { title: 'Conectar y evolucionar', text: 'Integramos inventario, facturación o comunicaciones cuando el flujo central ya es estable.' },
    ],
    faqs: [
      { title: '¿Debemos dejar de recibir pedidos por WhatsApp?', text: 'No necesariamente. Puede seguir siendo un canal de conversación. El objetivo es que la información operativa termine en un registro estructurado y no dependa únicamente del historial del chat.' },
      { title: '¿Los clientes tienen que crear una cuenta?', text: 'Depende del proceso. Algunas soluciones usan formularios o enlaces simples; otras requieren autenticación para consultar historial, precios o estados privados.' },
      { title: '¿Puede conectarse con inventario y facturación?', text: 'Sí, cuando los sistemas ofrecen mecanismos de integración adecuados. Revisamos APIs, reglas, responsables y manejo de errores antes de comprometer la conexión.' },
      { title: '¿Qué pasa con pedidos incompletos o excepcionales?', text: 'El diseño contempla validaciones y rutas de revisión humana. La meta no es ocultar excepciones, sino hacerlas visibles y evitar que avancen sin control.' },
      { title: '¿Podemos empezar solo con el registro y seguimiento?', text: 'Sí. Centralizar pedidos y estados puede ser una primera etapa valiosa; después se priorizan automatizaciones según los datos y la adopción observada.' },
    ],
    caseStudy: { name: 'NexusPOS', href: '/proyectos/nexus-pos/', label: 'Ver el flujo comercial de NexusPOS', text: 'NexusPOS conecta la venta con inventario, clientes, caja, domicilios y reportes dentro de una misma operación comercial.' },
    related: [
      { href: '/servicios/desarrollo-crm/', label: 'CRM para clientes y pedidos' },
      { href: '/servicios/software-a-la-medida/', label: 'Sistemas de pedidos a la medida' },
      { href: '/soluciones/automatizar-procesos/', label: 'Automatizar tareas posteriores al pedido' },
    ],
    ctaTitle: 'Convierte tus pedidos en un proceso visible',
    ctaText: 'Cuéntanos por dónde llegan, quién los gestiona y dónde aparecen los errores. Te ayudamos a definir una primera etapa.',
    ctaLabel: 'Analizar mi gestión de pedidos',
    whatsappMessage: 'Hola, quiero digitalizar la gestión de pedidos de mi empresa y quisiera solicitar un diagnóstico.',
  },
  'automatizar-procesos': {
    kind: 'solution',
    kicker: 'Trabajo que avanza solo cuando debe',
    h1: 'Automatiza procesos manuales en tu empresa',
    lead: 'Identifica tareas repetitivas, traspasos y alertas que pueden ejecutarse de forma consistente sin quitarle al equipo el control de las decisiones importantes.',
    intro: [
      'Un proceso manual no es negativo por definición. Algunas actividades necesitan conversación, juicio o adaptación. El problema aparece cuando personas capacitadas dedican horas a copiar información, revisar condiciones predecibles o avisar que ocurrió algo que el sistema ya podría detectar.',
      'La automatización responsable separa reglas de excepciones. Define qué puede ejecutarse, qué debe registrarse y cuándo una persona necesita intervenir. Así se ahorra tiempo sin construir una caja negra que nadie sabe supervisar cuando cambia la operación.',
    ],
    problemsTitle: 'Tareas que consumen tiempo sin aportar criterio',
    problemsIntro: 'Observamos frecuencia, claridad de las reglas, disponibilidad de datos y consecuencias de un error antes de decidir qué automatizar.',
    problems: [
      { title: 'Copiar y pegar información', text: 'Los mismos datos viajan manualmente entre formularios, hojas, correos y plataformas internas.' },
      { title: 'Revisiones periódicas', text: 'Una persona abre sistemas para comprobar si apareció un pago, vencimiento, solicitud o cambio de estado.' },
      { title: 'Mensajes repetitivos', text: 'Confirmaciones, recordatorios o avisos se redactan una y otra vez a partir de información ya disponible.' },
      { title: 'Asignación manual de trabajo', text: 'Las tareas se reparten revisando condiciones conocidas, disponibilidad o categoría, pero sin una regla compartida.' },
      { title: 'Consolidación de reportes', text: 'Cada cierre exige descargar, limpiar y unir datos de varias fuentes antes de poder interpretarlos.' },
    ],
    audienceTitle: 'Cuándo un proceso está listo para automatizarse',
    audienceIntro: 'Una buena oportunidad tiene un inicio reconocible, datos accesibles y un resultado que puede comprobarse. Las excepciones también deben poder identificarse.',
    audience: [
      { title: 'La secuencia se repite con frecuencia', text: 'El equipo puede describir pasos similares para muchos casos y las variaciones importantes son conocidas.' },
      { title: 'Las reglas ya existen', text: 'Aunque estén en la memoria de una persona, hay condiciones claras que permiten decidir la siguiente acción.' },
      { title: 'El error manual tiene consecuencias', text: 'Una omisión provoca demoras, mensajes incorrectos, diferencias de datos o trabajo de corrección en etapas posteriores.' },
    ],
    solutionsTitle: 'Opciones para reducir trabajo manual',
    solutionsIntro: 'La solución puede ser una integración pequeña, una función dentro del sistema actual o un flujo nuevo. Elegimos la intervención menos compleja que resuelve el problema.',
    solutions: [
      { title: 'Sincronización de datos', text: 'Actualiza información entre herramientas autorizadas y registra qué se transfirió o por qué no pudo completarse.' },
      { title: 'Alertas por condiciones', text: 'Notifica a la persona adecuada cuando un caso vence, cambia de estado o requiere revisión.' },
      { title: 'Generación automática', text: 'Crea documentos, resúmenes o mensajes a partir de datos validados y plantillas controladas.' },
      { title: 'Asignación y seguimiento', text: 'Distribuye tareas mediante reglas visibles y mantiene estados, responsables y tiempos en un flujo común.' },
      { title: 'Asistencia inteligente', text: 'Clasifica o resume contenido cuando las fuentes, límites y puntos de validación humana están definidos.' },
    ],
    benefitsTitle: 'Mejoras que una automatización debe demostrar',
    benefits: [
      { title: 'Menos pasos por caso', text: 'El trabajo avanza sin que una persona deba mover datos o recordar cada transición.' },
      { title: 'Mayor consistencia', text: 'Las mismas condiciones producen acciones equivalentes y las excepciones quedan visibles.' },
      { title: 'Tiempos de respuesta menores', text: 'Los eventos activan el siguiente paso cuando ocurren, sin esperar una revisión manual programada.' },
      { title: 'Capacidad de supervisión', text: 'El equipo conoce qué se ejecutó, puede revisar errores y conserva una ruta para intervenir.' },
    ],
    processTitle: 'De la tarea repetitiva a un flujo controlado',
    processIntro: 'Automatizamos después de simplificar. Cada etapa debe tener una responsabilidad clara y una forma de comprobar el resultado.',
    process: [
      { title: 'Documentar el proceso actual', text: 'Seguimos casos reales y registramos herramientas, datos, decisiones, tiempos y excepciones.' },
      { title: 'Elegir el punto de mayor valor', text: 'Priorizamos por impacto, frecuencia, viabilidad y riesgo, no por novedad tecnológica.' },
      { title: 'Definir reglas y salida', text: 'Acordamos qué inicia el flujo, qué valida, qué produce y cuándo debe detenerse.' },
      { title: 'Crear controles y registros', text: 'Diseñamos permisos, alertas y trazabilidad antes de conectar las acciones automáticas.' },
      { title: 'Probar escenarios', text: 'Validamos funcionamiento normal, datos incompletos, servicios no disponibles y recuperación.' },
      { title: 'Medir antes de ampliar', text: 'Comparamos el proceso y extendemos la automatización solo cuando la primera etapa es estable.' },
    ],
    faqs: [
      { title: '¿Cualquier tarea repetitiva puede automatizarse?', text: 'No siempre conviene. Revisamos volumen, estabilidad, accesos, costo de implementación y riesgo. Algunas tareas mejoran más al simplificarse que al automatizarse.' },
      { title: '¿Necesitamos cambiar todas nuestras herramientas?', text: 'No. Si las plataformas actuales ofrecen integraciones confiables, podemos conectarlas. Cuando no las ofrecen, evaluamos alternativas sin prometer accesos que no existen.' },
      { title: '¿La automatización puede tomar decisiones?', text: 'Puede aplicar reglas acordadas. Las decisiones ambiguas, sensibles o de alto impacto deben mantener revisión humana y una explicación suficiente.' },
      { title: '¿Qué mantenimiento requiere?', text: 'Las APIs, reglas y procesos cambian. Por eso se necesitan monitoreo, registros y una revisión cuando alguna herramienta o condición del negocio se modifica.' },
      { title: '¿Cómo empezamos sin arriesgar la operación?', text: 'Con un flujo acotado, pruebas sobre casos reales y supervisión durante la adopción. También conservamos una ruta manual para situaciones no previstas.' },
    ],
    caseStudy: { name: 'Lia', href: '/proyectos/lia/', label: 'Conocer las capacidades de Lia', text: 'Lia combina consulta de información, análisis y acciones asistidas para apoyar automatizaciones con contexto empresarial.' },
    related: [
      { href: '/servicios/automatizacion-de-procesos/', label: 'Servicio de automatización de procesos' },
      { href: '/servicios/software-a-la-medida/', label: 'Software a la medida' },
      { href: '/soluciones/digitalizar-pedidos/', label: 'Digitalizar pedidos' },
    ],
    ctaTitle: 'Encuentra una primera automatización con impacto real',
    ctaText: 'Descríbenos una tarea que tu equipo repite. Revisamos datos, reglas y herramientas para valorar si conviene automatizarla.',
    ctaLabel: 'Analizar mi proceso',
    whatsappMessage: 'Hola, quiero analizar qué procesos manuales puedo automatizar en mi empresa.',
  },
  'mejorar-presencia-digital': {
    kind: 'solution',
    kicker: 'Que te encuentren y te entiendan',
    h1: 'Mejora la presencia digital de tu empresa',
    lead: 'Alinea tu página web, Google Business, Maps y contenido para que una persona encuentre información confiable y sepa cómo avanzar.',
    intro: [
      'La presencia digital no es tener perfiles abiertos en muchas plataformas. Es ofrecer una imagen coherente del negocio cuando alguien lo busca por nombre, por servicio o por una necesidad que todavía no asocia con una empresa concreta.',
      'Una dirección desactualizada, una web lenta o una descripción genérica pueden romper la confianza incluso antes de la primera conversación. El diagnóstico reúne esos puntos para decidir qué corregir primero y evitar acciones aisladas que no mejoran el recorrido completo.',
    ],
    problemsTitle: 'Señales de una presencia digital fragmentada',
    problemsIntro: 'Revisamos lo que ve una persona y también lo que pueden interpretar los buscadores: información, estructura, rastreo y señales de entidad.',
    problems: [
      { title: 'Datos diferentes entre canales', text: 'Teléfonos, horarios, nombres o enlaces no coinciden y generan dudas sobre cuál información sigue vigente.' },
      { title: 'Una página desactualizada', text: 'El sitio ya no representa los servicios, carga con dificultad en móvil o no ofrece un camino de contacto claro.' },
      { title: 'Baja visibilidad en Google', text: 'La empresa no aparece para búsquedas relevantes o las páginas indexadas no corresponden con lo que ofrece actualmente.' },
      { title: 'Google Business sin aprovechar', text: 'Categorías, servicios, fotografías, horarios o enlaces están incompletos y no apoyan la decisión del cliente.' },
      { title: 'Contenido sin enfoque', text: 'La comunicación habla de la empresa en términos generales, pero no responde problemas ni preguntas de quienes buscan una solución.' },
    ],
    audienceTitle: 'Empresas que necesitan ordenar antes de invertir más',
    audienceIntro: 'Es útil tanto para negocios sin web como para empresas con activos digitales que crecieron sin una arquitectura común.',
    audience: [
      { title: 'Negocios que dependen de recomendaciones', text: 'Reciben contactos por voz a voz, pero la búsqueda posterior no ofrece suficiente información para confirmar confianza.' },
      { title: 'Empresas con servicios nuevos', text: 'La oferta evolucionó, mientras el sitio y los perfiles continúan describiendo una versión anterior del negocio.' },
      { title: 'Equipos que publican sin resultados claros', text: 'Mantienen redes o campañas, pero el destino no explica el servicio ni permite medir conversaciones relacionadas.' },
    ],
    solutionsTitle: 'Cómo se organiza una presencia digital coherente',
    solutionsIntro: 'No todas las empresas necesitan los mismos canales. Construimos una base controlable y elegimos mejoras según la forma real en que los clientes buscan y deciden.',
    solutions: [
      { title: 'Diagnóstico de activos', text: 'Inventariamos perfiles, páginas, datos de contacto, indexación y rutas de conversión para encontrar inconsistencias.' },
      { title: 'Propuesta y arquitectura web', text: 'Ordenamos servicios, problemas, casos y preguntas en páginas que responden intenciones diferentes.' },
      { title: 'Google Business y Maps', text: 'Alineamos información verificable, categorías, servicios, enlaces y recursos del perfil con el sitio oficial.' },
      { title: 'SEO técnico y contenido', text: 'Corregimos rastreo, metadata, enlazado y contenido para que cada página tenga un propósito reconocible.' },
      { title: 'Contacto contextual', text: 'Ubicamos formularios o mensajes de WhatsApp según el servicio para iniciar conversaciones con mejor información.' },
    ],
    benefitsTitle: 'Una experiencia consistente desde la búsqueda hasta el contacto',
    benefits: [
      { title: 'Mayor claridad', text: 'La persona entiende qué resuelve la empresa, para quién es relevante y qué puede hacer a continuación.' },
      { title: 'Más confianza', text: 'Los datos y mensajes coinciden entre canales y están respaldados por casos e información comprobable.' },
      { title: 'Mejor rastreabilidad', text: 'El sitio ofrece rutas indexables, metadata propia y enlaces que ayudan a descubrir servicios y soluciones.' },
      { title: 'Inversión priorizada', text: 'El diagnóstico distingue correcciones fundamentales de mejoras posteriores para evitar dispersar tiempo y presupuesto.' },
    ],
    processTitle: 'Cómo diagnosticamos y mejoramos la presencia digital',
    processIntro: 'Observamos la experiencia como un sistema: búsqueda, resultado, página, evidencia y contacto deben contar la misma historia.',
    process: [
      { title: 'Buscar como lo haría un cliente', text: 'Revisamos consultas, resultados, perfiles y mensajes que aparecen alrededor de la empresa y sus servicios.' },
      { title: 'Auditar sitio y canales', text: 'Evaluamos contenido, experiencia móvil, rastreo, datos y coherencia de contacto.' },
      { title: 'Definir la arquitectura', text: 'Relacionamos problemas, servicios, casos y llamadas a la acción en una estructura fácil de explorar.' },
      { title: 'Corregir fundamentos', text: 'Priorizamos información incorrecta, indexación, rendimiento y páginas que no explican la oferta.' },
      { title: 'Fortalecer contenido y evidencia', text: 'Añadimos detalles útiles y casos verificables sin inventar cifras, ubicaciones o testimonios.' },
      { title: 'Medir y mantener', text: 'Observamos visibilidad y contactos, y definimos cómo actualizar la información cuando el negocio cambie.' },
    ],
    faqs: [
      { title: '¿Qué incluye el diagnóstico digital?', text: 'Revisamos página web, Google, Maps, canales de contacto y señales técnicas básicas. También relacionamos la presencia externa con procesos internos como gestión de clientes o pedidos cuando afectan la conversión.' },
      { title: '¿Necesito una página web si ya uso redes sociales?', text: 'Una web ofrece un activo controlado para explicar servicios, organizar contenido y conectar búsquedas con acciones. Las redes pueden apoyar el alcance, pero dependen de formatos y reglas externas.' },
      { title: '¿Pueden mejorar lo que ya tenemos?', text: 'Sí. Conservamos identidad y tecnología cuando funcionan. La recomendación puede ser reorganizar contenido, corregir datos o crear páginas específicas, no necesariamente reemplazar todo.' },
      { title: '¿Cómo se relaciona con SEO local?', text: 'El SEO local es una parte de la presencia digital cuando la ubicación o zona de servicio influye en la búsqueda. También deben funcionar el sitio, el mensaje y el contacto posterior.' },
      { title: '¿Prometen más clientes?', text: 'No inventamos garantías. Mejoramos las condiciones para ser encontrado, comprendido y contactado; el resultado comercial también depende de demanda, competencia, oferta y seguimiento.' },
    ],
    caseStudy: { name: 'Nativhaus', href: '/proyectos/native-haus/', label: 'Ver el caso de Nativhaus', text: 'Nativhaus muestra cómo una experiencia web puede organizar un catálogo visual y llevar cada interés hacia una conversación de cotización.' },
    related: [
      { href: '/servicios/desarrollo-web/', label: 'Desarrollo web para empresas' },
      { href: '/servicios/seo-local/', label: 'SEO local y Google Business' },
      { href: '/soluciones/digitalizar-pedidos/', label: 'Digitalizar el contacto posterior' },
    ],
    ctaTitle: 'Descubre qué puede mejorar en la presencia de tu negocio',
    ctaText: 'Analizamos tus activos digitales y te mostramos oportunidades concretas para ganar claridad, visibilidad y mejores conversaciones.',
    ctaLabel: 'Solicitar diagnóstico digital gratuito',
    whatsappMessage: 'Hola, quiero mejorar la presencia digital de mi empresa y quisiera solicitar el diagnóstico gratuito de NovaLine.',
  },
}

export const SERVICE_ROUTE_KEYS = new Set<RouteKey>([
  'software-a-la-medida',
  'desarrollo-crm',
  'automatizacion-de-procesos',
  'desarrollo-web',
  'seo-local',
])

export const SOLUTION_ROUTE_KEYS = new Set<RouteKey>([
  'reemplazar-excel',
  'digitalizar-pedidos',
  'automatizar-procesos',
  'mejorar-presencia-digital',
])
